### ISSUE TITLE
Wrong curriculum link in website

### ISSUE THREAD

**Issue by joao** [LDSSA/ds-prep-course#37]
On the prep course [website](http://www.lisbondatascience.org/prep-course/) the link to see the curriculum, in more detail, is incorrect.

It should be:
`https:///docs.google.com/spreadsheets/d/165U7Y9ll0v5oKykIileYOTb7GcMPyQkkl18E-5-h_8k/edit#gid=2018895387`  

When at the present is:
`http://www.lisbondatascience.org/prep-course/clkn/https/docs.google.com/spreadsheets/d/165U7Y9ll0v5oKykIileYOTb7GcMPyQkkl18E-5-h_8k/edit#gid=2018895387`

![screenshot 2020-04-19 at 02 00 36](https://user-images.githubusercontent.com/1041/79676810-b1de9300-81e1-11ea-85c6-ba19aa9b22c6.png)

**Comment by PedroGFonseca** [comment]
Trippy. Can reproduce on Safari, but can't reproduce on Brave. 

Clicking the button does nothing, opening in new tab works on brave, and on safari leads to broken link. 

@minhhoang1023 any clues? The easiest fix may be to just move away from html entirely and add a button, may save us some pain.

**Comment by minhhoang1023** [comment]
@PedroGFonseca Yeh pretty weird. It works on Chrome if I open as a new tab, but not as a button. 
@dominguezmaria do you think if we could add a button as Pedro suggested?

**Comment by dominguezmaria** [comment]
changed it to a button, but there is still a weird error going on

<img width="561" alt="Screenshot 2020-04-22 at 10 13 45" src="https://user-images.githubusercontent.com/16541888/79964024-0738cf80-8482-11ea-9423-572537839c72.png">

will check later today :)

**Comment by dominguezmaria** [comment]
Replaced the link with one that seems to make it work!
@minhhoang1023 can you try it out (just to double check it works), and reopen if needed?
