### ISSUE TITLE
Final Project - TicTacToe

### ISSUE THREAD

**Issue by almeidar** [LDSSA/ds-prep-course#69]
Typo: above // below

![image](https://user-images.githubusercontent.com/9257740/82466224-095d7080-9ab8-11ea-90ed-99bbbe757904.png)

**Comment by Juliana-R** [comment]
This seems to have been corrected: https://github.com/LDSSA/ds-prep-course/blob/master/Week%209/SLU15%20-%20Final%20Project/Exercise%20notebook.ipynb. Will close this issue @ruimgf FYI.
