### ISSUE TITLE
Issue in activating Python virtual environments

### ISSUE THREAD

**Issue by Rishi174** [LDSSA/ds-prep-course#7]
I created a virtual environment in python using the following command in Windows Command Prompt.
python3 -m venv sample

This created a directory named sample but when I try to activate the environment using the following command: sample\Scripts\activate.bat, I am able to activate the environment but '"C:\WINDOWS\System32\chcp.com"' is not recognized as an internal or external command,
operable program or batch file.

The above message is being displayed. What does this mean and how it affects the environment.
Please help. Thanks in advance.
![Screenshot (60)](https://user-images.githubusercontent.com/39018637/77243314-ac1b7f00-6c2e-11ea-98dc-139d4745df43.png)

**Comment by buedaswag** [comment]
Hey @Rishi174 thank you for posting the issue!

I'm sorry to say that we dont support windows on our guides or on our learning materials, however we do support running Linux on WSL or VMware which you can do on windows.
Please refer to [this guide ](https://github.com/LDSSA/ds-prep-course#data-science-prep-course-repository) on how to setup for the course (it includes detailed instructions on how to create virtual environments).
